### ISSUE TITLE
Create Git tutorial

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Tutorials#12]
***What***: Develop a tutorial issue template that links to resources to guide developers through how to learn Git. Focus the tutorial on using the [Fork git client GUI](https://git-fork.com/).

***Why***: To provide developers with enough background info so that they can start contributing to our repositories. Use Fork because it has an intuitive interface and supports both Windows and Mac.

***Where***: Create issues in the [Tutorials](https://github.com/Uvic-Robotics-Club/Tutorials) repository.

***Subtasks***:
- [x] Look up existing videos and tutorials that use Fork
- [x] Look up tutorials for Git that don't rely on the command line
- [x] Create a tutorial issue that can be duplicated for anyone that needs it
- [x] Test out the issue with one member to see if it is clear
