### ISSUE TITLE
Establish coding standards

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Tutorials#13]
***What***: Create a document that developers can follow and adhere to when they are writing code. Ideally, it will follow industry coding standards.

***Why***: To provide all developers with a consistent idea of how their code is expected to look like, which is important when a project has a large number of collaborators. This will also emphasize proper coding techniques to encourage the reusability of our software in the future.

***Where***: Put them in a Wiki/Page (whatever was decided in [this issue](https://github.com/Uvic-Robotics-Club/Scheduler/issues/16)).

***Subtasks***:
- [ ] Look at existing standards in archived repository
- [ ] Look into PEP-8 standard
- [ ] Look at C++ standard
- [ ] Find good resources for coding style
- [ ] Write document with the common things that new members will look for
- [ ] Link good resources
