### ISSUE TITLE
New member tutorial

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Tutorials#3]
***Why***: To learn how version control works so that you can contribute to our repositories. We are starting off with a Git GUI (Fork), rather than the command line, because it is better for teaching Git concepts. After becoming proficient with Fork, you will be able to learn git on the command line a lot quicker (if you so desire). We will all use Fork to create an supportive environment where everyone is familiar with the same software and can assist each other. This tutorial is offered as videos that you can follow along, because it lets you learn at your own pace while getting hands-on experience.

***Dependencies***: Before completing this tutorial, make sure that you have completed your assigned "New Member Tutorial" issue.

***Subtasks***:

**Set up**
- [ ] Download [Fork client](https://git-fork.com/) (works for Windows and Mac).

**Learn**
To learn how to use Git, follow along with videos from [Zell Liew's Youtube Channel](https://www.youtube.com/channel/UCwIu7m0WpCNXiKZfysX54Zg). These videos will give you an excellent background on how Git works, and you can follow along at the same time. Watch the videos in order and check-off each task.
- [ ] 1. Watch [Setting up a Git Client](https://youtu.be/0z2vRogzbMQ) (13m 40s)
* _Note: Zell mentions GitKraken as an alternative, but recently GitKraken has reduced their free tier to no longer allow developers to work with private branches, so if you wanted to try this out for your homework assignments then you will need to pay $$._
* _Note: Zell briefly demonstrates how to initialize a repository with the command line. If you are using Windows and you want to try this, then you will need to install git for the command line. He doesn't use this in any of his future videos, so it is up to you if you want to experiment. For now, we will focus on using Fork._
- [ ] 2. Watch [Your first Git commit](https://youtu.be/nsORVjJTkeI) (7m 18s)
- [ ] 3. Watch [Pushing to a Git remote](https://youtu.be/dqRN8IXvsOg) (12m 49s)
* _Note: Zell's information about Github not offering free, private repositories is out-of-date. As of 2019, Github [allows developers on the free-tier to work in a private repository with up to 3 collaborators](https://github.com/pricing)._
* _Note: Zell uses SSH to connect to his remote repository. This might require you to do some googling to learn how to generate a set of keys for this. If you want an easier way, just click on the 'HTTPS' button and use that link instead._
- [ ] 4. Watch [Pulling from a Git remote](https://youtu.be/6x7CGpEKUXo) (5m 35s)
- [ ] 5. Watch [Cloning a Git repository](https://youtu.be/GYZBxXmrfWU)  (6m 59s)
- [ ] 6. Watch [Resolving Git conflicts](https://youtu.be/qLFj3H0j998) (9m 58s)
- [ ] 7. Watch [What is a Git branch?](https://youtu.be/yARRMa9zssw) (9m 4s)
- [ ] 8. Watch [Managing your Git branches with Git Flow](https://youtu.be/AlcKgpedAO0) (18m 1s) **~OPTIONAL**
* _Note: We will not use Git Flow, but if you are looking to get a developer co-op position soon, then this will give you an edge. The same goes for the other videos listed here as optional_
- [ ] 9. Watch [Semantic Versioning](https://youtu.be/rTZ35Subk9U) (5m 47s) **~OPTIONAL**
- [ ] 10. Watch [How to use Git stashes as a temporary storage](https://youtu.be/pmpGsPDPLrI) (3m 6s)
- [ ] 11. Watch [How to submit a pull request](https://youtu.be/D9CfagSgdVo) (16m 8s)
- [ ] 12. Watch [How to review and edit a pull request](https://youtu.be/UpBpb0j7IKA) (7m 39s)
- [ ] 13. Watch [Git Tags](https://youtu.be/59OgWy4BO90) (2m 40s) **~OPTIONAL**
- [ ] 14. Watch [Undoing changes in Git](https://youtu.be/za-DSrhiXJY) (9m 24s)
- [ ] 15. Watch [What not to save into a Git repository](https://youtu.be/grKh2Sl35bE) (3m 55s)
- [ ] 16. Watch [How to use the gitignore file](https://youtu.be/xlQIABDgTOs) (2m 31s)

**Demonstrate**
Now, you will have a solid grasp of how to interact and contribute to Github repositories, so try it out with our [Test](https://github.com/Uvic-Robotics-Club/Test) repository:

- [ ] 1. Clone the [Test](https://github.com/Uvic-Robotics-Club/Test) repository
- [ ] 2. Create a branch
- [ ] 3. Commit some text
- [ ] 4. Push your changes
- [ ] 5. Create a pull request with @s-sparrow as a reviewer
* _Note: Typically, at this point, on this current 'Learn to use Git' issue you would click on 'Linked pull requests' in the sidebar and link the pull request to this issue so that we can keep track of them. However, that step can't be done here because your pull request is in the 'Test' repository, while the 'Learn to us Git' issue is in the 'Tutorials' repository._
- [ ] 6. After your reviewer has accepted your pull request, you can merge it to the master branch

If you are confused about any of these tasks, then you are likely not the only one! Provide feedback to @s-sparrow.

In a future issue, we will discuss how to create _good_ git commits! :)```
