### ISSUE TITLE
New member tutorial

### ISSUE THREAD

**Issue by s-sparrow** [Uvic-Robotics-Club/Tutorials#4]
***What***: Complete the following tutorial that will introduce you to Slack, CIRC, and github projects. Check-off each box as you complete the tasks.

***Why***: To introduce new members to our workflow.

***Subtasks***:

**Github**:
- [x] Since you are now starting this issue, go to the [New Software Members](https://github.com/orgs/Uvic-Robotics-Club/projects/10) project board and drag and drop this issue from ‘To Do’ to ‘In Progress’. When you are dragging and dropping, make sure to click on the white-space in the issue. Make sure that you are moving the issue that is assigned to you, and not someone else!
- [x] Change your Github avatar to something that you like. This will make it easier to identify who is assigned to each task when viewing the project boards.

**Slack**
- [x] Get invitation and join our Slack channel.
- [x] Join the #software Slack channel.
- [x] Navigate to your profile settings: click on your name in the top left > click 'Profile & account' > click 'Edit Profile'
- [x] Add the name that you prefer to be called by as your ‘Display name’.
- [x] Add your full name to the 'Full name' section.
- [x] Add your position (for instance, “Software Member”) to the ‘What I do’ section.
- [x] Set your profile photo to a photo of yourself. This is extremely useful so that other team members can get to know your face/name. It also helps the Mechanical and Electrical teams find you if they need to contact you but don’t know your name yet.

**Competition**
- [x] Visit [CIRC main page](https://circ.cstag.ca/) and watch the 2019 Canadian International Rover Challenge Wrap-Up Video on the main page
- [x] Visit [CIRC competition tasks](https://circ.cstag.ca/2020/tasks/) and read through all five of the CIRC 2020 Competition Tasks. To get you started, there is a short summary of these tasks in our #software Slack channel.

**Software Team Plan**
- [x] Navigate to the UVic Robotics [organization projects page](https://github.com/orgs/Uvic-Robotics-Club/projects).
- [x] Look over the Rover Roadmap project board. This gives a broad overview of all of the components that are needed for us to enter the CIRC competition. It is a good idea to get familiar with it.
- [x] Look over the February Sprint project board. This is the workflow that our team will follow:

1. _To do_: Holds issues that are yet to be started
2. _In progress_: Holds issues that are currently in progress
3. _Review in progress_: Holds issues that have an active pull request (you will learn about pull requests soon)
4. _Reviewer approved_: Holds issues where all reviewers have approved the corresponding pull request
5. _Done_: Holds issues that are completed and no longer require any more work.

By the end of February, all issues should be in the Done category.

- [x] Notice how some issues have someone assigned to them, which is signified by their Github profile picture in the bottom-right of the issue
- [x] Notice how some issues have labels (eg. High priority) attached to them
- [x] Click on the title text of any issue so that the issue’s preview pops up on the right-side of the screen. Then click on “Go to issue for full details” at the bottom of the page. This is what a full issue looks like, which a single member will work on.
- [x] If it is not obvious to others that your Github username matches you, then add (at least) your first name to your Github profile. This will make it easier to identify who is assigned to what issue.

**Misc**
- [x] Navigate back to the [New Software Members](https://github.com/orgs/Uvic-Robotics-Club/projects/10) project board and notice that your issue has a status bar, which corresponds to the number of subtasks you have checked-off. When you are assigned an issue with subtasks, make sure to check them off (at least) before weekly meetings. This helps your team lead track your progress.
- [x] If you have any questions or feedback about any of the above tasks, then message Sarah.
- [x] When you have checked off all of the boxes, navigate back to the project board that this issue is in and move the issue from ‘In progress’ to ‘Done’ :)
